name       : qt6-5compat
version    : 6.3.0
release    : 6
source     :
    - https://download.qt.io/official_releases/qt/6.3/6.3.0/submodules/qt5compat-everywhere-src-6.3.0.tar.xz : 2b199be780c50d9214512b922d94cb240b0412fd63f459e356b76102cad1713e
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt 5 compatibility library for Qt 6
description: |
    The Qt 5 Core Compat module contains the Qt Core APIs which will be no longer supported in Qt 6 and therefore were removed from Qt 6. The module is provided to facilitate the transition to Qt 6.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(icu-i18n)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
