name       : qt6-5compat
version    : 6.5.1
release    : 7
source     :
    - https://download.qt.io/official_releases/qt/6.5/6.5.1/submodules/qt5compat-everywhere-src-6.5.1.tar.xz : ae992b295fefabef2445beb3a8ec31c40fa0fb2c01603eaf2acfdb4a0054fb83
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt 5 compatibility library for Qt 6
description: |
    The Qt 5 Core Compat module contains the Qt Core APIs which will be no longer supported in Qt 6 and therefore were removed from Qt 6. The module is provided to facilitate the transition to Qt 6.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(icu-i18n)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
