name       : qt6-5compat
version    : 6.2.2
release    : 2
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.2/submodules/qt5compat-everywhere-src-6.2.2.tar.xz : a5bb33d9df1d99e5afc21b0d0a36b79aa98829e2b1bee03c811ad69b79276bad
license    :
    - GFDL-1.3-or-later
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : desktop.qt
summary    : Qt 5 compatibility library for Qt 6
description: |
    The Qt 5 Core Compat module contains the Qt Core APIs which will be no longer supported in Qt 6 and therefore were removed from Qt 6. The module is provided to facilitate the transition to Qt 6.
builddeps  :
    - pkgconfig(Qt6Core)
    - pkgconfig(icu-i18n)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
